### ISSUE TITLE
如何使用 github 上最新的插件代码？

### ISSUE THREAD

**Issue by lijunru-hub** [intellism/vscode-comment-translate#143]
我在使用 remote 模式时，出现了，启动失败问题。整个插件不能使用。想更新到 github 上最新的代码，请问怎么操作？

我的版本：2.2.4 2022/7/20 11:12:20

**Comment by Cherrs** [comment]
先安装vsce
`npm install -g @vscode/vsce`
clone代码
`npm install`
`vsce package`
目录下面会有一个打包好的插件 拖进vscode就可以用了

**Comment by lijunru-hub** [comment]
使用最新的代码 vsce paceage 有下面的错误

/home/xxxx/node-v10.9.0-linux-x64/lib/node_modules/vsce/out/package.js:136
    return (translations ?? [])
                          ^

SyntaxError: Unexpected token ?
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by lijunru-hub** [comment]
目前的vscode版本是不支持 remote 翻译的，能否尽快上线新版本？

**Comment by intellism** [comment]
v2.3.0 已发布
