### ISSUE TITLE
插件调试启动报错 , 恳求能够得到帮助

### ISSUE THREAD

**Issue by Super1Windcloud** [intellism/vscode-comment-translate#231]
- 这是扩展主机的报错

Activating extension 'intellsmi.comment-translate' failed: Module build failed: Error: ENOENT: no such file or directory, open 'A:\Github_Learning_Project\comment_translate\node_modules\vscode-textmate\release\main.js'. 

--- 
- 然后是调试控制台
```Unable to load the "nx" package from the workspace. Please ensure that the proper dependencies are installed locally.
Note: Using the "preview" debug extension
vscode-custom-css is active!
Application directory a:\VScodeMicrosoft VS Code\resources\app\out
Main HTML file a:\VScodeMicrosoft VS Code\resources\app\out\vs\code\electron-sandbox\workbench\workbench.html
*,javascript,javascriptreact,typescript,typescriptreact,vue,vue-postcss,vue-sugarss,vue-html,json,jsonc,graphql,dart,sql,go,java,php,jade,python,swift,markdown
Looking for parseable documents...
Found no documents
[2024-08-07 00:25:48] [error] [packageFileWatcher] could not find 'a:\Github_Learning_Project\test.md' project file
TypeError: Cannot read properties of undefined (reading 'length')
    at variables (A:\VScode\plugin_extension\extensions\jnoortheen.nix-ide-0.3.3\node_modules\vscode-variables\index.js:6:55)
    at transformConfigValueByVscodeVariables (A:\VScode\plugin_extension\extensions\jnoortheen.nix-ide-0.3.3\src\utils.ts:16:13)
    at Ho.get (A:\VScode\plugin_extension\extensions\jnoortheen.nix-ide-0.3.3\src\configuration.ts:22:12)
    at Ho.get formatterPath [as formatterPath] (A:\VScode\plugin_extension\extensions\jnoortheen.nix-ide-0.3.3\src\configuration.ts:28:17)
    at Object.<anonymous> (A:\VScode\plugin_extension\extensions\jnoortheen.nix-ide-0.3.3\src\formatter.ts:13:10)
    at Module._compile (A:\Github_Learning_Project\comment_translate\lib\internal\modules\cjs\loader.js:1373:14)
    at Object.Module._extensions..js (A:\Github_Learning_Project\comment_translate\lib\internal\modules\cjs\loader.js:1432:10)
    at Module.load (A:\Github_Learning_Project\comment_translate\lib\internal\modules\cjs\loader.js:1215:32)
    at Module._load (A:\Github_Learning_Project\comment_translate\lib\internal\modules\cjs\loader.js:1031:12)
    at Function.c._load (A:\Github_Learning_Project\comment_translate\lib\electron\js2c\node_init.js:2:13801)
    at Function.E._load (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6051)
    at Function.i._load (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:174:31787)
    at Function.o._load (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:139:34334)
    at Module.require (A:\Github_Learning_Project\comment_translate\lib\internal\modules\cjs\loader.js:1240:19)
    at Module.require (a:\VScode\plugin_extension\extensions\humao.rest-client-0.25.1\dist\extension.js:12:12993)
    at require (A:\Github_Learning_Project\comment_translate\lib\internal\modules\helpers.js:179:18)
    at Function.i [as __$__nodeRequire] (a:\VScodeMicrosoft VS Code\resources\app\out\bootstrap-fork.js:3:98)
    at m.xb (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:174:32966)
    at async Promise.all (index 0) {stack: 'TypeError: Cannot read properties of undefine…174:32966)
    at async Promise.all (index 0)', message: "Cannot read properties of undefined (reading 'length')"}
TypeError: Cannot read properties of undefined (reading 'length')
    at variables (A:\VScode\plugin_extension\extensions\jnoortheen.nix-ide-0.3.3\node_modules\vscode-variables\index.js:6:55)
    at transformConfigValueByVscodeVariables (A:\VScode\plugin_extension\extensions\jnoortheen.nix-ide-0.3.3\src\utils.ts:16:13)
    at Ho.get (A:\VScode\plugin_extension\extensions\jnoortheen.nix-ide-0.3.3\src\configuration.ts:22:12)
    at Ho.get formatterPath [as formatterPath] (A:\VScode\plugin_extension\extensions\jnoortheen.nix-ide-0.3.3\src\configuration.ts:28:17)
    at Object.<anonymous> (A:\VScode\plugin_extension\extensions\jnoortheen.nix-ide-0.3.3\src\formatter.ts:15:15)
    at Module._compile (A:\Github_Learning_Project\comment_translate\lib\internal\modules\cjs\loader.js:1373:14)
    at Object.Module._extensions..js (A:\Github_Learning_Project\comment_translate\lib\internal\modules\cjs\loader.js:1432:10)
    at Module.load (A:\Github_Learning_Project\comment_translate\lib\internal\modules\cjs\loader.js:1215:32)
    at Module._load (A:\Github_Learning_Project\comment_translate\lib\internal\modules\cjs\loader.js:1031:12)
    at Function.c._load (A:\Github_Learning_Project\comment_translate\lib\electron\js2c\node_init.js:2:13801)
    at Function.E._load (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6051)
    at Function.i._load (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:174:31787)
    at Function.o._load (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:139:34334)
    at Module.require (A:\Github_Learning_Project\comment_translate\lib\internal\modules\cjs\loader.js:1240:19)
    at Module.require (a:\VScode\plugin_extension\extensions\humao.rest-client-0.25.1\dist\extension.js:12:12993)
    at require (A:\Github_Learning_Project\comment_translate\lib\internal\modules\helpers.js:179:18)
    at Function.i [as __$__nodeRequire] (a:\VScodeMicrosoft VS Code\resources\app\out\bootstrap-fork.js:3:98)
    at m.xb (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:174:32966)
    at async Promise.all (index 0) {stack: 'TypeError: Cannot read properties of undefine…174:32966)
    at async Promise.all (index 0)', message: "Cannot read properties of undefined (reading 'length')"}
[INFO] 2024-08-06T16:25:51.938Z - Translations initialized.
[INFO] 2024-08-06T16:25:51.948Z - Extension activated!
 Quokka.js Live Share integration disabled, VSLS not found.
Figma for VS Code started activation
rejected promise not handled within 1 second: Error: command 'rest-client.fold-response' already exists
stack trace: Error: command 'rest-client.fold-response' already exists
    at d.registerCommand (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:205087)
    at Object.registerCommand (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:164:22263)
    at new _ (A:\VScode\plugin_extension\extensions\cweijan.vscode-office-3.3.10\out\extension.js:270:1886)
    at new y (A:\VScode\plugin_extension\extensions\cweijan.vscode-office-3.3.10\out\extension.js:266:5951)
    at Object.n.activate (A:\VScode\plugin_extension\extensions\cweijan.vscode-office-3.3.10\out\extension.js:126:3168)
Unable to read plugin config file plugin_dev_settings.json Error: ENOENT: no such file or directory, open 'c:\Users\superuse\AppData\Roaming\Code\User\globalStorage\figma.figma-vscode-extension\plugin_dev_settings.json'
    at readFileSync (A:\Github_Learning_Project\comment_translate\lib\fs.js:450:20)
    at t.readFileSync (A:\Github_Learning_Project\comment_translate\lib\electron\js2c\node_init.js:2:9900)
    at $w.readFileSync (a:\VScode\plugin_extension\extensions\vue.volar-2.0.28\dist\client.js:66:19404)
    at Object.s [as read] (a:\VScode\plugin_extension\extensions\figma.figma-vscode-extension-0.3.5\out\figma-for-vs-code.js:231:4488)
    at sze (a:\VScode\plugin_extension\extensions\figma.figma-vscode-extension-0.3.5\out\figma-for-vs-code.js:243:2206)
    at ize (a:\VScode\plugin_extension\extensions\figma.figma-vscode-extension-0.3.5\out\figma-for-vs-code.js:243:1257)
    at m.n (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6409)
    at m (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6372)
    at m.l (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5829) {errno: -4058, code: 'ENOENT', syscall: 'open', path: 'c:\\Users\\superuse\\AppData\\Roaming\\Code\\U…ma-vscode-extension\\plugin_dev_settings.json', stack: "Error: ENOENT: no such file or directory, ope…\api\\node\\extensionHostProcess.js:144:5829)", …}
arg1: Error: ENOENT: no such file or directory, open 'c:\Users\superuse\AppData\Roaming\Code\User\globalStorage\figma.figma-vscode-extension\plugin_dev_settings.json'\n    at readFileSync (node:fs:450:20)\n    at t.readFileSync (node:electron/js2c/node_init:2:9900)\n    at $w.readFileSync (A:\VScode\plugin_extension\extensions\vue.volar-2.0.28\dist\client.js:66:19404)\n    at Object.s [as read] (A:\VScode\plugin_extension\extensions\figma.figma-vscode-extension-0.3.5\out\figma-for-vs-code.js:231:4488)\n    at sze (A:\VScode\plugin_extension\extensions\figma.figma-vscode-extension-0.3.5\out\figma-for-vs-code.js:243:2206)\n    at ize (A:\VScode\plugin_extension\extensions\figma.figma-vscode-extension-0.3.5\out\figma-for-vs-code.js:243:1257)\n    at m.n (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6409)\n    at m (a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6372)\n    at m.l (a:\VScodeMicrosoft VS Co… …
f @ a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:148:6
e @ a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:47855
<anonymous> @ a:\VScodeMicrosoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:47723
info @ a:\VScode\plugin_extension\extensions\figma.figma-vscode-extension-0.3.5\out\figma-for-vs-code.js:176:55343
s @ a:\VScode\plugin_extension\extensions\figma.figma-vscode-extension-0.3.5\out\figma-for-vs-code.js:231:4618
sze @ a:\VScode\plugin_extension\extensions\figma.figma-vscode-extension-0.3.5\out\figma-for-vs-code.js:243:2206
Figma for VS Code active
``` 

手动安装vscode-textmate 也报错
> npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> oniguruma@7.2.3 install A:\Github_Learning_Project\comment_translate\node_modules\oniguruma
> node-gyp rebuild
````  

A:\Github_Learning_Project\comment_translate\node_modules\oniguruma>if not defined npm_config_node_gyp (node "A:\nvm_node_list\nvm\v12.22.12\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "A:\nvm_node_list\nvm\v12.22.12\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "A:\VS2022"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (A:\nvm_node_list\nvm\v12.22.12\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47) 
gyp ERR! stack     at A:\nvm_node_list\nvm\v12.22.12\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (A:\nvm_node_list\nvm\v12.22.12\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at A:\nvm_node_list\nvm\v12.22.12\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at A:\nvm_node_list\nvm\v12.22.12\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at A:\nvm_node_list\nvm\v12.22.12\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at A:\nvm_node_list\nvm\v12.22.12\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "A:\\nvm_node_list\\nodejs\\node.exe" "A:\\nvm_node_list\\nvm\\v12.22.12\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd A:\Github_Learning_Project\comment_translate\node_modules\oniguruma
gyp ERR! node -v v12.22.12
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@7.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@7.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\superuse\AppData\Roaming\npm-cache\_logs\2024-08-06T16_24_20_615Z-debug.log  
```

**Comment by intellism** [comment]
是如何启动调试的，在vscode里面已经配置过调试启动。
![image](https://github.com/user-attachments/assets/3f278bf5-5865-471e-9c33-82d2fcced0ff)

**Comment by Super1Windcloud** [comment]
我看你typescript Nodejs声明文件是 @type/node: "12.12  "     我才安装的Node12 版本

**Comment by intellism** [comment]
> 我看你typescript Nodejs声明文件是 @type/node: "12.12 " 我才安装的Node12 版本

嗯嗯。 这个是很早之前生成的了，内部api版本要求不高。wasm编译引入的时候比较晚了，没有测试过node v12是否编译的过。
