### ISSUE TITLE
报错,望修复

### ISSUE THREAD

**Issue by lifetin** [intellism/vscode-comment-translate#4]
c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\server\out\util\request-promise.js:9
            resolve(response.body);
                             ^

TypeError: Cannot read property 'body' of undefined
    at Request.request [as _callback] (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\server\out\util\request-promise.js:9:30)
    at self.callback (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\server\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Timeout._onTimeout (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\server\node_modules\request\request.js:852:16)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
[Info  - 上午12:24:29] Connection to server got closed. Server will restart.
[Error - 上午12:24:29] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:1983:42)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\main.js:126:15)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:1970:18)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at IPCMessageReader.AbstractMessageReader.fireClose (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at ChildProcess.<anonymous> (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\messageReader.js:253:61)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 上午12:24:29] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:1983:42)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\main.js:126:15)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:1970:18)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at IPCMessageReader.AbstractMessageReader.fireClose (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at ChildProcess.<anonymous> (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\messageReader.js:253:61)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 上午12:24:29] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:1983:42)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\main.js:126:15)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:1970:18)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at IPCMessageReader.AbstractMessageReader.fireClose (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at ChildProcess.<anonymous> (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\messageReader.js:253:61)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
Overwriting grammar scope name to file mapping for scope source.json.
Old grammar file: c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json\syntaxes\JSON.tmLanguage.json.
New grammar file: C:\Users\Administrator\.vscode\extensions\htwx.json-and-jsonc-1.0.1\syntaxes\JSON.tmLanguage.json
c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\server\out\util\request-promise.js:9
            resolve(response.body);
                             ^

TypeError: Cannot read property 'body' of undefined
    at Request.request [as _callback] (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\server\out\util\request-promise.js:9:30)
    at self.callback (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\server\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Timeout._onTimeout (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\server\node_modules\request\request.js:852:16)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
[Info  - 上午12:25:53] Connection to server got closed. Server will restart.
[Error - 上午12:25:53] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\main.js:825:25)
	at Object.dispose (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:57:35)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:1983:42)
	at LanguageClient.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\main.js:126:15)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-languageclient\lib\client.js:1970:18)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at closeHandler (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\main.js:221:26)
	at CallbackList.invoke (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:71:39)
	at Emitter.fire (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\events.js:135:36)
	at IPCMessageReader.AbstractMessageReader.fireClose (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\messageReader.js:135:27)
	at ChildProcess.<anonymous> (c:\Users\Administrator\.vscode\extensions\intellsmi.comment-translate-1.0.0\client\node_modules\vscode-jsonrpc\lib\messageReader.js:253:61)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
Overwriting grammar scope name to file mapping for scope source.json.
Old grammar file: c:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json\syntaxes\JSON.tmLanguage.json.
New grammar file: C:\Users\Administrator\.vscode\extensions\htwx.json-and-jsonc-1.0.1\syntaxes\JSON.tmLanguage.json

**Comment by lifetin** [comment]
[Error - 上午12:28:13] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot destructure property `commentLines` of 'undefined' or 'null'.
  Code: -32603 
[Error - 上午12:28:14] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot destructure property `commentLines` of 'undefined' or 'null'.
  Code: -32603 
[Error - 上午12:28:43] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot destructure property `commentLines` of 'undefined' or 'null'.
  Code: -32603 
[Error - 上午12:28:45] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot destructure property `commentLines` of 'undefined' or 'null'.
  Code: -32603 
[Error - 上午12:29:00] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot destructure property `commentLines` of 'undefined' or 'null'.
  Code: -32603

**Comment by lifetin** [comment]
![55](https://user-images.githubusercontent.com/10474968/55496714-42e3da00-5672-11e9-9846-a7118e9f5571.png)

还有3行注释的,也报错

**Comment by intellism** [comment]
> ![55](https://user-images.githubusercontent.com/10474968/55496714-42e3da00-5672-11e9-9846-a7118e9f5571.png)
> 
> 还有3行注释的,也报错

这个是什么语言

**Comment by intellism** [comment]
这里是两个问题。
  - response.body 不存在是google接口限制，已替换token版本，已修复；
  - commentLines 目前没定位，需要提供下 “系统、vscode版本、翻译的目前语言”

**Comment by intellism** [comment]
如果是有开启vpn,代理等，请关闭后再试试看。

**Comment by lifetin** [comment]
版本: 1.32.3 (user setup)
提交: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
日期: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

翻译目标是英到中文


然后我没有开vpn,
然后这个错误提示,不应该一直有提示的.因为只要一显示这个错误,这个底部的标签就被切到你这个日志窗口了.应该加个次数限制1-3次后不再显示相同的错误提示.

**Comment by lifetin** [comment]
不知道是不是你升级了下,现在不再弹窗这个错误了
然后我也开了vpn也正常,暂时没有发现什么错误.

然后还有个问题,发现这种格式的他不会提示

# This file tracks properties of this Flutter project.
# Used by Flutter tool to assess capabilities and perform upgrades etc.
#
# This file should be version controlled and should not be manually edited.

version:
  revision: 8661d8aecd626f7f57ccbcb735553edc05a2e713
  channel: stable

project_type: app


![44](https://user-images.githubusercontent.com/10474968/55898282-d5e1be80-5bf4-11e9-9c83-bd32d84f38cd.png)

**Comment by intellism** [comment]
v1.3.0 已修复。 建议已收到，先行评估下。  目前新增了字符串和用户变量名翻译，看看是否可以覆盖你的使用场景。

**Comment by intellism** [comment]
v1.3.1 已支持建议的选中文本翻译。  选中后，hover到选择区域显示翻译结果。
![image](https://user-images.githubusercontent.com/442894/56090162-bab2cf80-5ed0-11e9-9dd0-13433e528d37.png)
